removed base64 from contrib
ydb-platform/ydb-cpp-sdk pull request #108
Opened 2024-03-21 19:58 UTC by Shikaree68

2024-03-22 13:46 UTC, GitSparTV requested changes
Привет. Ошибки билда и конфликты в main появились.
Поправь

2024-03-25 14:45 UTC, GitSparTV requested changes
Привет! Оказалась не самая тривиальная библиотека, ты смог всё подключить.
Нужно убрать из GHA твои отладочные команды, оставил пару заметок заказчику, которые ему могут быть интересны.

2024-03-25 14:45 UTC, GitSparTV commented on .github/actions/prepare_vm/action.yaml
> +        cd
Вот это всё надо теперь убрать. Пользователю не нужно видеть `ls`-ки

2024-03-25 14:45 UTC, GitSparTV commented on README.md
Лишний пробел

2024-03-25 14:45 UTC, GitSparTV commented on library/cpp/string_utils/base64/base64.cpp
> +    IMPL.Decode(b, size, (char*)dst, &outLen, 0);
Отмечу для заказчика, что тут C-касты

2024-03-25 14:45 UTC, GitSparTV commented on library/cpp/string_utils/base64/base64.cpp
> +        void (*Encode)(const char* src, size_t srclen, char* out, size_t* outlen, int flags);
Для заказчика:

Имеет ли смысл после удаления библиотеки из репо иметь класс в таком виде?
Здесь раньше была логика, которая решала какую функцию использовать. Теперь она умеет это делать сама, если передан флаг 0.

> Set flags to 0 for the default behavior, which is runtime feature detection on x86, a compile-time fixed codec on ARM, and the plain codec on other platforms.

Теперь будет несколько индирекций при вызове:
```
        mov     edi, OFFSET FLAT:.LC0
        call    [QWORD PTR [rax]]
```

Есть вариант сделать известность на compile-time, например, сделать Encode/Decode как inline static methods.
```
        mov     edi, OFFSET FLAT:.LC0
        call    base64_encode(char const*)
```

2024-03-25 14:49 UTC, Gazizonoki commented on library/cpp/string_utils/base64/base64.cpp
> +        void (*Encode)(const char* src, size_t srclen, char* out, size_t* outlen, int flags);
Теперь в этом классе нет смысла, можно просто убрать его и использовать base64_encode/decode напрямую

2024-03-25 14:53 UTC, Gazizonoki commented on library/cpp/string_utils/base64/base64.cpp
> +    IMPL.Decode(b, size, (char*)dst, &outLen, 0);
Сейчас их исправлять смысла нет, но на будущее отмечу, что нужно будет исправить #110

2024-03-25 20:25 UTC, Gazizonoki requested changes

2024-03-25 20:25 UTC, Gazizonoki commented on library/cpp/string_utils/base64/base64.cpp
> +    base64_encode(b, size, (char*)dst, &outLen, 0);
Здесь должен быть decode

2024-03-25 20:25 UTC, Gazizonoki commented on library/cpp/string_utils/base64/ut/ya.make
> +    usr/local/
Эти изменения не нужны, текущая система сборки - cmake, ya.make пока руки не дошли вычистить. И даже так, usr/local/ нельзя указывать, не факт, что путь будет таким.

2024-03-25 20:25 UTC, Gazizonoki commented on .github/actions/prepare_vm/action.yaml
> +        sudo rm -r ./base64-0.5.2
Надо вставить пустую строку в конце файла

2024-03-25 20:25 UTC, Gazizonoki commented on README.md
> +sudo rm -r ./base64-0.5.2
Эту строку в README указывать не надо, репозиторий может еще понадобиться пользователю для деинсталляции

2024-03-25 20:25 UTC, Gazizonoki commented on .github/actions/prepare_vm/action.yaml
> +        cd
Надо делать единообразно во всем коде, либо `cd`, либо `cd ..`, а у тебя разночтение со строчкой выше

2024-03-26 08:47 UTC, Shikaree68 commented on library/cpp/string_utils/base64/ut/ya.make
> +    usr/local/
а что указать? Нашел - "зависимости библиотеки перечисляются через макрос PEERDIR. Здесь просто пишутся пути до папки с library либо с другим артефактом внутри, относительно корня репозитория."
если на удаление, то может просто пустым оставить?

2024-03-26 12:08 UTC, Gazizonoki commented on library/cpp/string_utils/base64/ut/ya.make
> +    usr/local/
Просто верни так, как было, чтобы этот файл не был виден в PR'е

2024-03-26 14:36 UTC, Gazizonoki approved these changes

2024-03-26 14:36 UTC, merged