Removed nayuki_md5_lib
ydb-platform/ydb-cpp-sdk pull request #115
Opened 2024-03-29 07:25 UTC by Jlucblu

Удалил библиотеку nayuki_md5 из contrib, определил как внешнюю.
Отличаются версии используемые в проекте и на сайте разработчика, для совместимости внесены исправления в код через cmake, приведены к изначальной версии.
Дополнительно исключен файл [md5-fast-x8664.S], в проекте нет упоминаний его использования.

2024-04-03 11:44 UTC, GitSparTV commented
#44

2024-04-03 11:44 UTC, GitSparTV commented
Конфликты с main веткой. Пофиксил

2024-04-04 05:55 UTC, Jlucblu commented
Сделал rebase, смержил ветки - конфликты должны пройти.
Так же немного изменил README (убрал export) и логику в Findnayuki_md5.cmake (убрал конфликт с правами доступа)

2024-04-08 19:21 UTC, GitSparTV commented
Нужно порешать конфликты, чтобы до вторника я мог посмотреть

2024-04-09 21:16 UTC, GitSparTV approved these changes
Привет. Всё посмотрел. Как же странно собирается эта библиотека...

2024-04-09 21:28 UTC, Jlucblu commented
> Привет. Всё посмотрел. Как же странно собирается эта библиотека...

Согласен с замечанием, в ней оказались нюансы =)
Вообще не понимаю ее предназначения, md5 сильно устаревший формат, и вроде бы SHA есть в проекте ...

2024-04-09 22:06 UTC, Gazizonoki requested changes

2024-04-09 22:06 UTC, Gazizonoki commented on cmake/Findnayuki_md5.cmake
Так библиотеки не подтягивают. Либо собранные архив или .so-шник лежат в системе и мы их ищем, либо если из сорсов, то подключают сабмодуль. Как я вижу, тут серьезная проблема с тем, что нет хедеров в репозитории. Значит помещаем сорсы как часть проекта, а в будущем думаем об избавлении от такой библиотеки. Но чтобы искать сорсы по системе, а хедеры генерить во время сборки, так библиотеки точно подтягивать нельзя. Библиотека проблемная, я поэтому и флаг students-projects убрал c нее. Давай ты пока просто перенесешь в third_party через git mv и почистишь ее CMakeLists.txt, а то 6 версий - это последствия автогена, мы такого в проекте видеть не хотим

2024-04-09 22:06 UTC, Gazizonoki commented on README.md
> +## Testing
А это откуда взялось?

2024-04-09 22:06 UTC, Gazizonoki commented on library/cpp/digest/md5/ya.make
Я же убрал ya.make файлы, зачем вернул?

2024-04-09 22:06 UTC, Gazizonoki commented on library/cpp/testing/unittest/junit.cpp
> +#include <string_view>
Для чего перенес string_view?

2024-04-09 22:06 UTC, Gazizonoki commented on library/cpp/testing/unittest/utmain.cpp
> +#include <format>
Зачем добавлять сюда эти хедеры? Они же дублируют те, что выше

2024-04-10 09:02 UTC, GitSparTV reviewed
Добавил замечание

2024-04-10 09:02 UTC, GitSparTV commented on .github/actions/prepare_vm/action.yaml
> +        mkdir ~/nayuki_md5/ && cd ~/nayuki_md5/
Кстати, тут выделяется библиотека от остальных тем, что используется `~` в путях

2024-04-10 09:02 UTC, GitSparTV commented on README.md
> +mkdir ~/nayuki_md5/ && cd ~/nayuki_md5/
И здесь это более критично, чем в GHA

2024-04-11 22:15 UTC, Jlucblu commented on .github/actions/prepare_vm/action.yaml
> +        mkdir ~/nayuki_md5/ && cd ~/nayuki_md5/
Это сделано преднамеренно, для решения конфликта доступа.
Можно создать хэдер через sudo, но тогда не получится внести в него изменения из cmake файла, не хватит прав.
Если размещать файл по домашнему пути, из-под этого же пользователя можно собрать проект без описанной проблемы.

2024-04-28 02:43 UTC, closed without merging