Issue #91 remove googletest from contrib
ydb-platform/ydb-cpp-sdk pull request #116
Opened 2024-03-29 12:51 UTC by tsayukov

Issue #91

Добавил также `CMakeLists` файлы для юнит тестов внутри `library/cpp/testing`, чтобы проверить, что всё работает. Это временное решение, т.к. пока мне не ясно как у нас будут включаться тесты: через какой-нибудь ключ `ENABLE_TESTING`, который через `if`-ы будет всё включать (`enable_testing()` и остальное), или иным образом. По той же причине `find_package(GTest)` пока объявлен как `REQUIRED`, в идеале он должен искаться только, если включена поддержка тестирования.
Впрочем, задача была, чтобы библиотека собиралась, и сейчас она собирается.

Из интересного:
* Думаю, что из-за легаси сборки через `ya make` некоторые вещи перестали работать корректно сейчас. Например, предполагаю, что раньше `ya make` самостоятельно устанавливал макро определения `ARCADIA_ROOT` и `ARCADIA_BUILD_ROOT`, как пути до верхнего уровня source- и build-файлов. В библиотеке так же был определён макрос `__SOURCE_FILE__` (его реализация в `util/system/src_root.h`), который брал текущий путь до файла и обрезал у него префикс, если мог, так, чтобы получился путь, относительный верхнего уровня source- или build-файлов, в зависимости, где текущий файл находился. Из-за того, что первые макро определения отсутствовали, макрос ничего не обрезал, и это ломало остальные функции. Я исправил это, как мог, не трогая `ARCADIA_ROOT` и `ARCADIA_BUILD_ROOT`, если они определены, но на случай, если нет, вместо них подставляются пути из `CMAKE_SOURCE_DIR` и `CMAKE_BINARY_DIR`. Это починило падающие тесты.
* Единственный тест, который до сих пор не работает, это получение корректного пути до `gdb` (`library/cpp/testing/common/ut/env_ut.cpp`, Runtime, GdbPath). С ним пока не получилось разобраться.

2024-03-30 08:59 UTC, tsayukov commented
Разрешил конфликт, сейчас меняю `GetEnv` и `SetEnv` на `std::getenv` и `std::setenv` и исправляю окружающий их код.

2024-03-30 13:43 UTC, GitSparTV approved these changes
Привет! Посмотрел файлы, оставил комментарии, чтобы твои пояснения тоже почитать.

2024-03-30 13:43 UTC, GitSparTV commented on library/cpp/testing/common/env.cpp
> +    if (!workPath.empty()) {
А теперь он перестал работать через operator bool?

2024-03-30 13:43 UTC, GitSparTV commented on library/cpp/testing/common/network.cpp
> +        if (givenRange.find(':') != std::string::npos) {
Это фикс после другого PR?

2024-03-30 13:43 UTC, GitSparTV commented on library/cpp/testing/unittest/junit.cpp
> +            escaped.insert(escaped.end(), static_cast<const char*>(s.data()), reinterpret_cast<const char*>(i));
А там `.data()` возвращает какой-то другой тип?

2024-03-30 13:43 UTC, GitSparTV commented on library/cpp/testing/unittest/registar_ut.cpp
> +        UNIT_ASSERT_TEST_FAILS(stringsUnequal("42", "42"s));
А что тестирует этот файл? Функцию `stringsUnequal`?

2024-03-30 14:32 UTC, tsayukov commented on library/cpp/testing/common/env.cpp
> +    if (!workPath.empty()) {
Раньше вместо `std::string` был собственный `TString`, у которого был оператор `bool` (который внутри проверял, пустая ли строка), а у стандартных строк его нет

2024-03-30 14:38 UTC, tsayukov commented on library/cpp/testing/common/network.cpp
> +        if (givenRange.find(':') != std::string::npos) {
Поменяли внутренние классы строк на стандартные в PR #82
Просто раньше библиотека для тестирования была исключена из сборки, поэтому только сейчас исправил.

2024-03-30 14:53 UTC, tsayukov commented on library/cpp/testing/unittest/junit.cpp
> +            escaped.insert(escaped.end(), static_cast<const char*>(s.data()), reinterpret_cast<const char*>(i));
Да, поскольку `s` неконстантная строка, `data()` будет `char*` возвращать. Но на самом деле я здесь недостаточно хорошо подумал. Здесь не нужна `s` как `std::string`, она здесь не меняется, и достаточно будет принимать её как `std::string_view`, тогда и кастовать ничего не нужно будет. Спасибо!

2024-03-30 15:04 UTC, tsayukov commented on library/cpp/testing/unittest/registar_ut.cpp
> +        UNIT_ASSERT_TEST_FAILS(stringsUnequal("42", "42"s));
Я так понимаю, что `stringsUnequal` ввели, чтобы не писать каждый раз длинный макрос `UNIT_ASSERT_STRINGS_UNEQUAL`, и на самом деле тестируют его, что он работает с различной комбинацией типов строк. Я здесь только поменял явные конструкторы строк и вьюшек на литералы, чтобы было покороче. Вообще, насколько могу судить по комментариям в коде, эта часть тестирующей библиотеки существует только из-за того, что уже какое-то количество юнит-тестов написано с её помощью. И для новых юнит-тестов её не рекомендуют использовать

2024-04-01 16:43 UTC, GitSparTV approved these changes
Посмотрел. По твоей части всё хорошо. Тут вперемешку коммиты заказчика. Смутило, что в источниках GetEnv требует два параметра, в коде NUtil::GetEnv использует один. А где-то вообще `std::getenv` напрямую используется.

2024-04-01 17:02 UTC, tsayukov commented
> Посмотрел. По твоей части всё хорошо. Тут вперемешку коммиты заказчика. Смутило, что в источниках GetEnv требует два параметра, в коде NUtil::GetEnv использует один. А где-то вообще `std::getenv` напрямую используется.

У `NUtils::GetEnv` на самом деле тоже два, просто последний по умолчанию пустая строка! Для нас это удобно, потому что мы можем сразу результат проверять, пустая строка или нет.
В остальной части библиотеки редко нужно было получать значение переменной окружения (а менять вообще никогда), наверное, поэтому убрали старые `GetEnv` и `SetEnv` и заменили на однострочные проверки.

2024-04-01 17:16 UTC, Gazizonoki requested changes
В PR попало много лишних изменений, видимо из-за мерджа из main. Если авторство строк поменялось в git blame, придется ребейзится. Если нет, можешь оставить. В некоторых файлах в конце нет пустых строк. Такое обозначается красным кирпичом, надо поправить. 5 версий CMakeLists под разные ОС тоже надо убрать. Везде это делать не прошу, но если потрогал CMakeLists, надо поправить. Серьезных замечаний нет, поправь мелочи.

2024-04-01 17:16 UTC, Gazizonoki commented on library/cpp/testing/gtest_extensions/pretty_printers.h
> +    *stream << NUtils::Quote(value).c_str();
c_str больше тут не нужен, std::basic_stream можно напрямую выводить в std::ostream

2024-04-01 17:16 UTC, Gazizonoki commented on library/cpp/testing/gtest_extensions/pretty_printers.h
> +//     *stream << NUtils::Quote(std::basic_string<TCharType, TCharTraits>{value}).c_str();
Тоже можно убрать c_str()

2024-04-01 17:19 UTC, Gazizonoki commented
> > Посмотрел. По твоей части всё хорошо. Тут вперемешку коммиты заказчика. Смутило, что в источниках GetEnv требует два параметра, в коде NUtil::GetEnv использует один. А где-то вообще `std::getenv` напрямую используется.
> 
> У `NUtils::GetEnv` на самом деле тоже два, просто последний по умолчанию пустая строка (то, что возвращаем из функции, если не удалось получить значение переменной окружения)! Для нас это удобно, потому что мы можем сразу результат проверять, пустая строка или нет. В остальной части библиотеки редко нужно было получать значение переменной окружения (а менять вообще никогда), наверное, поэтому убрали старые `GetEnv` и `SetEnv` и заменили на однострочные проверки.

SetEnv вообще не использовалось, GetEnv использовалось редко, мне показались эти функции излишними, вот и убрал. Но в testing они используются активно, так что правильное решение, что ты вернул их под неймспейсом

2024-04-01 21:53 UTC, Gazizonoki approved these changes

2024-04-01 21:54 UTC, merged