replase TArrayRef to std::span (#79)
ydb-platform/ydb-cpp-sdk pull request #118
Opened 2024-04-01 16:18 UTC by zenonneo11

replace TarrayRef to std::span. Removed tests for TarrayRef/

2024-04-02 19:10 UTC, GitSparTV commented
В табличке задача ещё in progress. Статус верный?

2024-04-05 15:47 UTC, Gazizonoki requested changes

2024-04-05 15:47 UTC, Gazizonoki commented on library/cpp/containers/stack_array/stack_array.h
> +    class TStackArray {
Теперь у этого класса нет смысла, у него ни одного метода нет теперь. Раз оно скомпилировалось, TStackArray не нужен. Просто убери всю директорию

2024-04-05 15:47 UTC, Gazizonoki commented on library/cpp/diff/diff.h
> +using TConstSpan = std::span<const T>;
Зачем нужен этот using? Число вводимых символов он почти не уменьшил, можно `std::span<const T>` напрямую писать

2024-04-05 15:47 UTC, Gazizonoki commented on library/cpp/monlib/metrics/histogram_snapshot.cpp
> +    IHistogramSnapshotPtr ExplicitHistogramSnapshot(std::span<const TBucketBound> bounds, std::span< const TBucketValue> values, bool shrinkBuckets) {
Лишний пробел между `<` и `const`.

2024-04-05 15:47 UTC, Gazizonoki commented on library/cpp/threading/future/wait/wait.h
> +#include<span>
Нужен пробел между `#include` и `<span>`

2024-04-05 15:47 UTC, Gazizonoki commented on util/generic/fwd.h
> +struct TGUID;
Не хватает пробела в конце файла

2024-04-05 17:47 UTC, Gazizonoki requested changes

2024-04-05 17:47 UTC, Gazizonoki commented on library/cpp/diff/diff.h
> +        for (size_t i = 0; i <= n && (e1 != (s1.data() + s1.size()) || e2 != (s2.data() + s2.size()));) {
А скобки вокруг `s1.data() + s1.size()` и `s2.data() + s2.size()` не лишние? Кажется у `+` приоритет больше, чем у сравнения

2024-04-05 17:47 UTC, Gazizonoki commented on library/cpp/diff/diff_ut.cpp
> +    std::string_view Common(const TConstSpan<const char>& str) const {
Так и осталось тут

2024-04-05 18:25 UTC, closed without merging