Remove jwtcpp from contrib #38
ydb-platform/ydb-cpp-sdk pull request #124
Opened 2024-04-03 16:37 UTC by PACCBET23

удаление jwt-cpp

2024-04-05 20:07 UTC, GitSparTV requested changes
Привет! Удаление библиотеки выглядит успешным, а вот её использование странным.

Посмотри, пожалуйста, пробелы и /usr/local

2024-04-05 20:07 UTC, GitSparTV commented on cmake/external_libs.cmake
> +
Пробел появился

2024-04-05 20:07 UTC, GitSparTV commented on ydb/library/login/login.cpp
> +#include </usr/local/include/jwt-cpp/jwt.h>
Глобальные пути к библиотекам никогда не указывают.

Нет возможности CMake-у найти эту библиотеку просто через `jwt-cpp/jwt`? find_package ведь должен помочь

2024-04-05 22:34 UTC, PACCBET23 commented on cmake/external_libs.cmake
> +
Лишние пробелы убрал  [bdfef5b](https://github.com/ydb-platform/ydb-cpp-sdk/pull/124/commits/bdfef5b89f33070a904c3e59cd1dc7be07d40cdd)

2024-04-05 22:34 UTC, PACCBET23 commented on ydb/library/login/login.cpp
> +#include </usr/local/include/jwt-cpp/jwt.h>
и правда. исправил [bdfef5b](https://github.com/ydb-platform/ydb-cpp-sdk/pull/124/commits/bdfef5b89f33070a904c3e59cd1dc7be07d40cdd)

2024-04-08 19:22 UTC, GitSparTV commented
Есть конфликты

2024-04-08 19:56 UTC, PACCBET23 commented
> Есть конфликты

исправлено

2024-04-09 21:18 UTC, GitSparTV approved these changes
Отлично!

2024-04-09 21:18 UTC, GitSparTV commented on .github/actions/prepare_vm/action.yaml
> +          libiconv-1.15 base64-0.5.2 brotli-1.1.0 jwt-cpp-0.7.0 v0.7.0.tar.gz
@Gazizonoki Вот про это я говорил отдельно. Если это ок, что тут просто номер версии хранится в папке, то ок.

2024-04-09 21:26 UTC, Gazizonoki requested changes

2024-04-09 21:26 UTC, Gazizonoki commented on .github/actions/prepare_vm/action.yaml
> +          libiconv-1.15 base64-0.5.2 brotli-1.1.0 jwt-cpp-0.7.0 v0.7.0.tar.gz
Да, я видел твой коммент, это действительно может привести к проблемам, тут надо пофиксить. Другие папки я сам исправлю, надо исправить jwt. @PACCBET23 замени v0.7.0.tar.gz на jwt-cpp-0.7.0.tar.gz, у wget есть для этого опция -O

2024-04-09 21:26 UTC, Gazizonoki commented on .github/actions/prepare_vm/action.yaml
> +          libiconv-1.15 base64-0.5.2 brotli-1.1.0 jwt-cpp-0.7.0 v0.7.0.tar.gz
В остальных местах не надо, это моя недоработка

2024-04-09 21:26 UTC, Gazizonoki commented on clang.toolchain
> +set(ENV{CXX} clang++)
Что в этой строке поменялось? Надо вернуть к исходному виду

2024-04-10 11:44 UTC, PACCBET23 commented on clang.toolchain
> +set(ENV{CXX} clang++)
хороший вопрос,ответа на него у меня нет. файл откатил 
7b5a660

2024-04-10 11:45 UTC, PACCBET23 commented on .github/actions/prepare_vm/action.yaml
> +          libiconv-1.15 base64-0.5.2 brotli-1.1.0 jwt-cpp-0.7.0 v0.7.0.tar.gz
исправлено 
7b5a660

2024-04-10 12:20 UTC, GitSparTV commented on clang.toolchain
> +set(ENV{CXX} clang++)
Скорее всего line ending отличался, либо newline был, потом пропал.

2024-04-10 12:38 UTC, Gazizonoki approved these changes

2024-04-10 12:38 UTC, merged