52 rm fastlz from contrib
ydb-platform/ydb-cpp-sdk pull request #125
Opened 2024-04-04 08:23 UTC by Add-JDHero

FastLZ перенес в submodule

2024-04-05 17:36 UTC, Gazizonoki requested changes

2024-04-05 17:36 UTC, Gazizonoki commented on cmake/external_libs.cmake
> +add_library(FastLZ STATIC
Зачем STATIC? Мы можем захотеть динамически линковать fast_lz. Тут это указывать не надо

2024-04-06 12:47 UTC, Add-JDHero commented
Сделал ребейз до актуального main и исправил замечания

2024-04-08 14:46 UTC, Gazizonoki approved these changes

2024-04-08 14:46 UTC, merged