TDeque to std::deque
ydb-platform/ydb-cpp-sdk pull request #133
Opened 2024-04-08 04:25 UTC by Lomzovat

2024-04-08 07:30 UTC, GitSparTV requested changes
Привет! Много времени прошло, но у нас были другие задачи.

Кроме прямой замены нужно посмотреть остался ли смысл от кода, где использовались деки. Комментирование – это прошлый век, у нас есть Git :-) 
Приберись в классе и тестах

2024-04-08 07:30 UTC, GitSparTV commented on library/cpp/http/io/compression.h
> +
Пробел лишний

2024-04-08 07:30 UTC, GitSparTV commented on util/generic/deque.h
> +/*template <class T, class A>
Если кроме деки тут ничего не осталось, нужно удалить файл

2024-04-08 07:30 UTC, GitSparTV commented on util/generic/deque_ut.cpp
> -    using container = TDeque<int>;
Тесты для STL деки не нужны

2024-04-08 07:30 UTC, GitSparTV commented
Fixes #58

2024-04-09 21:24 UTC, GitSparTV requested changes
К сожалению, пока не всё. Появились новые файлы, которые надо именно удалить

2024-04-09 21:24 UTC, GitSparTV commented on util/generic/deque.pxd
> +/*from libcpp.deque cimport deque
Это питоновский экспортер. Деки больше нет. От файла можно избавиться

2024-04-10 13:51 UTC, Gazizonoki approved these changes

2024-04-10 13:52 UTC, merged