Issue #93 remove libc compat from contrib
ydb-platform/ydb-cpp-sdk pull request #214
Opened 2024-04-25 20:11 UTC by tsayukov

Issue #93

Задача в том, чтобы отказаться от использования libc_compat.

Части libc_compat, которые больше не используются в ydb-cpp-sdk и которые можно спокойно убрать:
- [x] `getservbyname/`: функция `getservbyname` и все её помощники. Ранее она была нужна, потому что у llvm msan до сих пор нет interceptor-обёртки для неё (чтобы убедиться в этом, можно написать простой main c ней, скомпилировать с `-fsanitize=memory` и через `readelf -Ws` и `grep` посмотреть таблицу символов), и включение санитайзера могло выдавать ложноположительные результаты.
- [x] `include/ifaddrs/`. Ранее `ifaddrs.h` добавлялся для Андроида с API level <24; сейчас это не целевая платформа, а также в текущей либе убрали соответствующий c-файл, так что можно не обращать на хедер внимания. Все остальные `#include <ifaddrs.h>` в ydb-cpp-sdk включаются через `#if` только для Unix-like систем и ссылаются на glibc. Для других платформ подключаются системные хедеры этих платформ с аналогичным функционалом.
- [x] `include/readpassphrase/`.
- [x] `random/`: функции `getentropy` и `getrandom`. Ранее были нужны из-за их отсутствия в более старых версиях glibc.
- [x] `ubuntu_14/`. Ранее файлы из этой папки нужны были, чтобы на старых версиях Ubuntu ниже 14 находились нужные символы, которых ещё не было в libc.

Из остальных хедеров, не считая `include/windows/sys/`, в ydb-cpp-sdk подключается только `contrib/libs/libc_compat/string.h`. В нём нас интересуют только функции `stricmp`, `strnicmp`, `strlcpy`, `strlcat` и `strlwr`.
- [x] Скопировать реализации `strlcpy`, `strlcat` и `strlwr` в `src/library/string_utils/helpers/helpers.h` как `size_t Strlcpy(char*, const char*, size_t)`, `size_t Strlcat(char*, const char*, size_t)`, `char* ToLower(char*)`. Далее заменить все вызовы на вызовы этих функций.
- [x] В `include/ydb-cpp-sdk/util/system/compat.h` определить макросы `stricmp` и `strnicmp`, которые в зависимости от платформы будут подставлять соответствующие функции из системного хедера `strings.h` или `string.h`.
- [x] Дополнительно:
  - [x] В `src/library/case_insensitive_string/case_insensitive_char_traits.h` привести трейт в соответствии с [требованиями](https://en.cppreference.com/w/cpp/named_req/CharTraits). Добавить юнит-тесты.

`include/windows/sys/` содержит два хедера: `queue.h` и `uio.h`. Первый, `sys/queue.h` больше не включается в ydb-cpp-sdk. Второй `sys/uio.h` (в нём нас интересуют две функции: `readv` и `writev`) включается при сборке под Windows, таким образом, для остальных систем будет искаться `sys/uio.h` из glibc, а для Windows выберется хедер в `include/windows/sys/`, поскольку он добавляется в инклюды libc_compat таргета в cmake. Соответственно, нужно переписать `readv` и `writev` в `src/library/coroutine/engine/network.cpp` и `src/util/network/socket.cpp` так, чтобы они работали и для Windows, и для платформ с glibc.

Однако, прежде чем перейти к этой задаче, бросается в глаза следующее (и такое встречается не раз):

```C++
ssize_t DoReadVector(SOCKET fd, TContIOVector* vec) noexcept {
  return readv(fd, (const iovec*) vec->Parts(), Min(IOV_MAX, (int) vec->Count()));
}
```

Проблема в том, что каст (забудем пока, что это C-style) из указателя к указателю _разных_ типов по стандарту может привести к UB, когда второй указатель попытаются разыменовать (см. [[[basic.lval] par.11]](https://timsong-cpp.github.io/cppwp/n4868/basic.lval#11), они же [Type aliasing](https://en.cppreference.com/w/cpp/language/reinterpret_cast)). На практике компиляторы в редких случаях эксплуатируют этот UB и скорее всего ничего не взорвётся, но я всё равно бы хотел избегать подобных кастов. Обычно такие штуки решают с помощью `std::memcpy`, `std::bit_cast`, а ещё в будущем, когда доимплементируют 23 стандарт, можно будет на месте использовать `std::start_lifetime_as` без копирований.

Везде, где вызывался `readv`/`writev`/`sendmsg`, наблюдался следующий паттерн:
- передаётся константный массив `TPart` (аналог `std::span`) и его длина;
- пытаются вызываться C-шные обёртки над системными вызовами (`readv` и его друзья), которые читают из или пишут в `TPart`ы из этого массив атомарно или хотя бы асинхронно (как в Windows);
- если не удаётся обработать все байты, копируют массив в буфер;
- считают, сколько байтов ещё осталось, возможно, меняют текущий `TPart` в буфере (сдвигают его указатель и уменьшают размер), если обработались только первые сколько-то байтов.
- возвращают количество обработанных байтов или код ошибки.

У нас уже есть класс-обёртка `TContIOVector` в `util/network/iovec.h`. Поэтому я решил добавить в него буфер, но в этом буфере сразу создавать нужные "C-шные" структуры типа `iovec` или `WSABUF`, исключая проблему небезопасных кастов. Подсказывает, как копировать (через `memcpy` или присваиванием), дополнительный трейт `TSpanAdapterTraits` в качестве шаблонного параметра у `TContIOVector`, который получился довольно многословным, но в нём я постарался учесть все случаи и сделать максимально обобщённым, а также добавил вспомогательные методы, чтобы можно было бы обращаться к полям "C-шной" структуры в общем случае, заранее не зная, что это за структура. Второй шаблонный параметр у `TContIOVector` -- это функтор, вызывающий соответствующую C-шную функцию. Причина, по которой я не захотел передавать функтор, например, в метод, -- не хотелось, чтобы один и тот же `TContIOVector`, изначально предназначенный только для чтения (`TPart`ы, допустим, указывают на константные строки, лежащие в readonly памяти), использовали для записи. Возможно, есть решение получше. У `TContIOVector` главные методы, которые делают всю работу, -- это `TryProcess` и `TryProcessAllBytes`. Соответственно:
- [x] Реализовать `TSpanAdapterTraits`.
- [x] Реализовать `TContIOVectorBase` и `TContIOVector` (базу сделал на случай возможного расширения, например, если захотим мувать `TContIOVector`-писателя в `TContIOVector`-читателя).
- [x] Реализовать функторы для `readv`/`writev`/`sendmsg`.
- [x] Поправить места вызова.
- [x] Проверить юнит тесты для сокетов и корутин, исправить ошибки.

Возможно, стоит подумать о том, чтобы заменить `TPart` (изначально он определён в `IOutputStream`) на `std::span<std::bytes>` и `std::span<const std::bytes>`? `TPart` плох тем, что он держит в себе `const void*`, а используют его как для чтения, так и для записи. Моему `TSpanAdapterTraits` всё равно, с каким span-подобным объектом работать.

Подумал, сильно ли повлияет на производительность сразу выделение буфера (`TTempBuf` до `64 * 1024` байтов переиспользует массив из готового списка, соответственно он не будет каждый раз просить новую память в куче). С одной стороны, массив span-ов сам по себе не очень большой, копируется моментально. С другой стороны, на очень больших размерах каждый раз будет выделяться память в куче. С третьей стороны, операции ввода-вывода (даже векторные) наверняка перебьют всё остальное.

<details>
  <summary>Вот мой бенчмарк:</summary>
  
Собирался с установленным `libbenchmark-dev`.

```CMake
find_package(benchmark REQUIRED)
add_executable(iovec_bm iovec_bm.cpp)
target_link_libraries(iovec_bm PRIVATE
  yutil
  cpp-testing-common
  benchmark::benchmark_main
)
```

  <details>
    <summary>Код:</summary>
    
```C++
#include "network/iovec.h"
#include <src/library/testing/common/env.h>

#include <ydb-cpp-sdk/util/memory/tempbuf.h>
#include <src/util/network/iovec.h>

#include <benchmark/benchmark.h>

#include <stdio.h>
#include <sys/uio.h>

#include <algorithm>
#include <cstdio>
#include <cstring>
#include <functional>
#include <iterator>
#include <limits>
#include <random>
#include <string>
#include <vector>

using namespace NUtils::NIOVector;

using TIOVector = TContIOVector<TIOVectorAdaptorTraits, TWriteVHandler>;

struct RandomWords {
    static constexpr std::size_t size = 5'000;

    std::vector<std::string> words;
    std::vector<TPart> parts;

public:
    RandomWords() {
        constexpr auto max_len = static_cast<std::size_t>(std::numeric_limits<unsigned char>::max());

        std::random_dev [...]

2024-04-28 16:43 UTC, tsayukov commented
- Переместил платформозависимый код в отдельный хедер `vectored_io.h`.
- Переписал свои тесты в `iovec_ut.cpp`, чтобы они выглядели более аккуратно, плюс добавил дополнительные проверки.
- Перенёс те тесты, которые потрогал, в `tests` (в том числе `socket_ut.cpp` и `coroutine_ut.cpp`). Остальные тесты из `util/network` и `library/coroutine` начну переносить после закрытия этого PR.

2024-05-04 09:24 UTC, GitSparTV approved these changes
Привет. Вот это PR. Очень здорово.
Как я понимаю, что всё сделано, но у тебя есть уточнения нужно ли делать std::byte.
По тем коммитам, что есть сейчас, посмотрел. Пока апрув

2024-05-04 10:00 UTC, tsayukov commented on src/library/string_utils/helpers/helpers.cpp
> +    bool TrySplit(std::string_view src,
Привет. Я ориентировался на [этот readme](https://github.com/ydb-platform/ydb-cpp-sdk/blob/main/src%2Futil%2FREADME.md), и там отступы внутри неймспейса такие же, как внутри класса. Ну и по коду, сколько видел, обычно такие же отступы. Впрочем, последнее слово за владельцами! Хотя, наверное, хорошо было бы завести какой-нибудь clang-format для этих целей?

И хорошо, что ты обратил на это внимание, потому что я перечитал readme и понял, что для нового хедера, который добавил, не создал парного cpp-файла, как просят делать в readme. Надо будет исправить.

2024-05-04 10:38 UTC, tsayukov commented on src/util/network/iovec.h
> +    class TContIOVector : public TContIOVectorBase<typename TCompatibilityTraits::LowLevel> {
Ты прав, эти изменения относятся к #93 косвенно; здесь я решил проявить инициативу, свою мотивацию я описал в начале PR.

Во-первых, желание убрать каст указатель-к-указателю непохожих с точки зрения стандарта структур (впрочем есть довольно популярное мнение, что такой каст законен, раз компиляторы в редких случаях эксплуатируют связанный с ним UB, но я не согласен с таким мнением).

Во-вторых, раз убираем каст, значит, нужно копировать массив структур в промежуточный буфер, и здесь я решил, что создавать такой буфер то тут, то там в разных частях библиотеки не очень хорошо, и лучше поместить такой буфер внутрь отдельного класса.

В-третьих, пусть этот отдельный класс делает всю грязную работу: передаёт управление хендлеру с сишной-функцией, обрабатывает столько байтов, сколько может, либо до первого прерывания, либо до первой ошибки. Таким образом, например, классы сокетов определяют свой собственный хендлер и только вызывают метод `TryProcessAllBytes`, не беспокоясь за детали. До этого, как мне кажется, сокеты делали слишком много не своей работы.

Впрочем, могу понять, если эти изменения покажутся избыточными. Готов выслушать любую критику!

2024-05-04 11:36 UTC, GitSparTV commented on src/util/network/iovec.h
> +    class TContIOVector : public TContIOVectorBase<typename TCompatibilityTraits::LowLevel> {
В реальной рабочей ситуации, скорее всего, бы отказали. Заводят новый тикет, в рамках которого ты уже внедряешь новые изменения

2024-05-06 00:35 UTC, tsayukov commented
Суммируя, надо было мне изначально создать новый тикет, и уже в нём питчить все серьёзные изменения в `TContIOVector`, которые бы помогли решить эту задачу, чтобы не раздувать этот PR. Тоже самое касается остальных сторонних улучшений.

2024-05-15 12:39 UTC, Gazizonoki requested changes
PR перегружен, читать его было сложно. Есть пару мелких замечаний, в остальном ок

2024-05-15 12:39 UTC, Gazizonoki commented on include/ydb-cpp-sdk/library/string_utils/helpers/helpers.h
Не понимаю, зачем было сдвигать весь файл? Явного формата у проекта конечно нет, но в общем по коду неймспейс не создает лишнего отступа. А так ты необоснованно переписываешь авторство строк в blame на себя.

2024-05-15 12:39 UTC, Gazizonoki commented on src/library/string_utils/helpers/helpers.cpp
> +    bool TrySplit(std::string_view src,
Отступы тут не нужны, за основу следует считать код в папке в client, все остальное - legacy, которое требуется для SDK, там формат может быть произвольным, а менять уже не получится - слишком много кода.

2024-05-15 13:45 UTC, tsayukov commented on include/ydb-cpp-sdk/library/string_utils/helpers/helpers.h
Понял, был неправ! А есть способ вернуть авторство строк (кроме самых радикальных)? Я пробовал делать `git checkout <коммит до изменения> -- <path/to/helpers.cpp>`, но после коммита этих изменений всё равно оставался автором

2024-05-15 16:40 UTC, Gazizonoki commented on include/ydb-cpp-sdk/library/string_utils/helpers/helpers.h
Вообще должно быть достаточно просто вернуть в тому виду, как было. Все равно все коммиты посквошатся и в итоге должен быть оригинальный автор

2024-05-16 15:19 UTC, Gazizonoki commented
Я починил сборку в CI, сделай rebase

2024-05-16 16:26 UTC, Gazizonoki approved these changes

2024-05-16 16:27 UTC, merged