relocate lib - nayuki_md5 to third_party
ydb-platform/ydb-cpp-sdk pull request #215
Opened 2024-04-28 02:47 UTC by Jlucblu

Из-за большого количества конфликтов после обновления репозитория, пришлось создать новую ветку с перемещением библиотеки в third_party. Предыдущий PR закрыл.

2024-05-04 09:31 UTC, GitSparTV approved these changes
Привет. Всё ок, добавить нечего

2024-05-06 15:43 UTC, Gazizonoki approved these changes

2024-05-06 15:43 UTC, Gazizonoki commented on contrib/libs/nayuki_md5/md5-fast-x8664.S
Почему этот файл удален? Это исходники под linux x86_64, вероятно эта версия более эффективна, ее тоже нужно перенести, и если мы на нужной платформе, использовать ее

2024-05-06 15:43 UTC, Gazizonoki commented on cmake/external_libs.cmake
> +target_include_directories(nayuki_md5 PUBLIC ${YDB_SDK_SOURCE_DIR}/third_party/nayuki_md5)
Не хватает пустой строки в конце файла

2024-05-06 15:44 UTC, Gazizonoki requested changes
Случайно аппрувнул)

2024-05-13 01:45 UTC, Jlucblu commented
В последней версии библиотеки автор изменил порядок аргументов в функции md5_compress. Поэтому пришлось также изменить порядок аргументов в местах вызова этой функции, чтобы они соответствовали её сигнатуре. Вносить изменения в файл с расширением .S может быть критично для стабильности работы, поскольку это может привести к нарушению работы ассемблерного кода и вызвать UB.

2024-05-15 12:44 UTC, Gazizonoki requested changes
В PR опять попали изменения, которые уже были в main. Прошу вас, делайте rebase, такие PR'ы потом ведь и ревьюить сложнее

2024-05-15 12:49 UTC, Jlucblu commented on third_party/nayuki_md5/nayuki_md5-fast-x8664.S
> +	movq  %rdi, %rbp
В новой версии библиотеки с сайта автора изменен порядок регистров, именно в связи с этим изменил порядок вызова в функциях, дабы не трогать регистры что бы не нарушить работу библиотеки.

2024-05-16 15:19 UTC, Gazizonoki commented
Я починил сборку, сделай rebase

2024-05-16 15:50 UTC, Gazizonoki commented
Ты еще замечание с пустыми строками не поправил

2024-05-16 16:06 UTC, Jlucblu commented
Вычистил лишние пробелы и переносы

2024-05-16 16:20 UTC, merged