190 Fix src/library/json tests (2.0)
ydb-platform/ydb-cpp-sdk pull request #250
Opened 2024-06-24 17:22 UTC by SvRgK11010

2024-06-24 17:31 UTC, SvRgK11010 commented
@GitSparTV дублирую

2024-06-24 19:50 UTC, GitSparTV approved these changes

2024-07-01 19:01 UTC, Gazizonoki requested changes

2024-07-01 19:01 UTC, Gazizonoki commented on tests/library/json/ut/CMakeLists.txt
Зачем создавать папку ut в tests? Это же тавтология, положи прямо в tests/library/json

2024-07-01 19:01 UTC, Gazizonoki commented on tests/library/digest/md5/md5_medium_ut.cpp
> +}
Для чего эти изменения?

2024-07-01 19:01 UTC, Gazizonoki commented on tests/library/json/ut/json_reader_ut.cpp
> +}
В конце файла должна быть пустая строка

2024-07-01 19:01 UTC, Gazizonoki commented on tests/library/json/ut/json_writer_ut.cpp
> +}
Нужная пустая строка в конце файла

2024-07-02 06:34 UTC, SvRgK11010 commented on tests/library/digest/md5/md5_medium_ut.cpp
> +}
Извиняюсь, не проходили локально тесты. Обновляла файл копипастом из основного репозитория

2024-07-02 06:44 UTC, SvRgK11010 commented
@Gazizonoki добрый день! внесла изменения

2024-07-02 17:31 UTC, Gazizonoki commented on tests/library/digest/md5/md5_medium_ut.cpp
> +}
Изменения все еще остались

2024-07-03 06:59 UTC, SvRgK11010 commented on tests/library/digest/md5/md5_medium_ut.cpp
> +}
Готово, откатила изменения

2024-07-03 11:14 UTC, Gazizonoki approved these changes

2024-07-03 11:15 UTC, merged