Integration tests
ydb-platform/ydb-cpp-sdk pull request #270
Opened 2024-07-22 11:14 UTC by stanislav-shchetinin

2024-07-26 19:31 UTC, Gazizonoki requested changes

2024-07-26 19:31 UTC, Gazizonoki commented on tests/integration/basic_example_it/basic_example.cpp
> +void PrintStatus(const TStatus& status) {
В этом методе нет больше необходимости

2024-07-26 19:31 UTC, Gazizonoki commented on tests/integration/basic_example_it/basic_example.cpp
> +void DescribeTable(TTableClient client, const std::string& path, const std::string& name) {
Ты тут не валидируешь результат DescibeTable, зачем тебе тогда вообще эту функцию вызывать? Она просто выводит информацию о таблице. Либо валидируй результат, либо удали функцию

2024-07-26 19:31 UTC, Gazizonoki commented on tests/integration/basic_example_it/basic_example.cpp
> +    std::cout << std::format("> Describe table: {}\n", name);
У тебя тут и везде ниже остался вот такой вывод. Оно не имеет смысла, ты просто засоряешь stdout

2024-07-26 19:31 UTC, Gazizonoki commented on tests/integration/basic_example_it/basic_example.cpp
> +    ThrowOnError(client.RetryOperationSync([path, name, &desc](TSession session) {
Лучше не кидать исключение, а проносить result прямиком до main, чтобы там сделать assert на result.IsSuccess(), а то если будет ошибка, мы и не поймем сразу, что это не из кишок вылетело, а так оно нам сразу подсветит. Везде ниже тоже лучше так сделать

2024-07-26 19:31 UTC, Gazizonoki commented on docker-compose.yaml
Зачем тебе compose здесь? Ты же нигде его не запускаешь

2024-07-26 19:31 UTC, Gazizonoki commented on tests/integration/basic_example_it/basic_example.cpp
> +void ThrowOnError(const TStatus& status) {
В этой функции смысла нет, ниже я объяснил, почему плохо кидать исключения тут

2024-07-26 19:31 UTC, Gazizonoki commented on tests/integration/basic_example_it/basic_example.cpp
> +TStatus FillTableDataTransaction(TSession session, const std::string& path) {
Тут и везде ниже надо переписать эти функции так, чтобы они возвращали result, а не TStatus

2024-07-26 19:31 UTC, Gazizonoki commented on tests/integration/basic_example_it/basic_example.cpp
> +            return FormatResultSetJson(rs, EBinaryStringEncoding::Unicode);
У scan query есть особенность, она возвращает result set в виде стрима, то есть по кусочкам. А тут ты получив первый кусок, сразу выходишь. Так делать не надо, у тебя вообщем нет гарантий на размер куска. Тут тебе скорее всего придется вытащить ScanQueryResult в main, вытаскивать result set'ы и объединять их. Не забывая, что каждый следующий кусок надо валидировать на ошибки

2024-07-27 18:50 UTC, stanislav-shchetinin commented on tests/integration/basic_example_it/basic_example.cpp
> +    ThrowOnError(client.RetryOperationSync([path, name, &desc](TSession session) {
Немного не понял что ты имеешь ввиду. Исключение TYdbErrorException обрабатывается в main - в случае, если оно вылетело, то вызывается FAIL(). Вылететь из кишок (как я понял, имеется ввиду функция объявленная вне basic_example.h) это исключение не может - т.к. TYdbErrorException объявлено в basic_example.h, следовательно, исключение извне обработано не будет. Если я не прав, можешь пояснить, пожалуйста?

2024-07-27 18:50 UTC, stanislav-shchetinin commented on tests/integration/basic_example_it/basic_example.cpp
> +            return FormatResultSetJson(rs, EBinaryStringEncoding::Unicode);
Нормально ли из ScanQueryResult возвращать vector json'ов и в main проверять что векторы совпали?

2024-07-27 18:50 UTC, stanislav-shchetinin commented on tests/integration/basic_example_it/main.cpp
> +    return {driver, path};
В него же кладется database. Не особо понял, что ты имеешь ввиду, но теперь я убрал path и просто возвращаю database.

2024-07-27 20:23 UTC, Gazizonoki commented on .github/workflows/tests.yaml
О как, поговорю с Лешей, зачем так сделали

2024-07-27 20:25 UTC, Gazizonoki commented on tests/integration/basic_example_it/basic_example.cpp
> +            return FormatResultSetJson(rs, EBinaryStringEncoding::Unicode);
Нет, не ок, разбиения ResultSet'a на парты не обязательно будут одинаковыми, хоть и result set одинаковый

2024-07-29 13:49 UTC, Gazizonoki requested changes
ut расшифровывается как unit tests. Так что tests/ut - тавтология получается, лучше сделать tests/unit

2024-07-29 13:49 UTC, Gazizonoki commented on examples/basic_example/basic_example.cpp
> +}
Вот тут пробел в конце файла пропал

2024-07-29 13:49 UTC, Gazizonoki commented on tests/integration/basic_example_it/basic_example.cpp
> +        std::cerr << "ScanQuery execution failure: " << resultScanQuery.GetIssues().ToString() << std::endl;
Тут надо исключение кидать

2024-07-29 13:49 UTC, Gazizonoki commented on tests/integration/basic_example_it/basic_example.cpp
> +                std::cerr << "ScanQuery execution failure: " << streamPart.GetIssues().ToString() << std::endl;
Опять таки, не надо выводить ничего, текст ошибки надо передавать тестовому фреймворку, пусть сам разбирается, как красиво вывести ее

2024-07-29 13:49 UTC, Gazizonoki commented on tests/integration/basic_example_it/basic_example.cpp
> +    auto resultScanQuery = client.StreamExecuteScanQuery(query, parameters).GetValueSync();
Все что ниже по хорошему надо обернуть в ретраер, чтобы тесты не флапали(сервер иногда может выдавать ошибку по внутренним причинам, например таблетки серверные переезжают, ничего страшного, такое можно поретраить)

2024-07-29 13:49 UTC, Gazizonoki commented on tests/integration/basic_example_it/main.cpp
> +        FAIL();
Ты игнорируешь текст ошибки, передай ее тестовому фреймворку: https://github.com/google/googletest/issues/181

2024-07-29 13:49 UTC, Gazizonoki commented on tests/integration/basic_example_it/main.cpp
> +#include <src/util/stream/file.h>
Для чего этот include?

2024-07-29 13:49 UTC, Gazizonoki commented on CMakePresets.json
> +        "ENDPOINT": "localhost:2136",
Вот тут забыл переименовать переменные окружения

2024-07-29 13:49 UTC, Gazizonoki commented on tests/integration/basic_example_it/basic_example.cpp
> +        std::cerr << "+Finished preparing query: PreparedSelectTransaction" << std::endl;
Лишний вывод, в тесте нам не интересно, из кэша запрос, или нет. Если тест не на кэш конечно) Но тут вроде не тот случай

2024-07-29 13:49 UTC, Gazizonoki commented on .github/workflows/tests.yaml
> +name: PR-check
Переименуй в Tests тогда, раз делим

2024-07-29 13:49 UTC, Gazizonoki commented on tests/integration/basic_example_it/main.cpp
> +    auto [driver, path] = GetRunArgs();
Ты тут не решил проблему с путем, мы все еще пишем в корень базы: в /local.

2024-07-29 13:51 UTC, Gazizonoki commented on tests/integration/basic_example_it/basic_example.cpp
> +            return FormatResultSetJson(rs, EBinaryStringEncoding::Unicode);
Добавь ORDER BY на все SELECT запросы, и будет ок

2024-07-29 21:36 UTC, Gazizonoki requested changes

2024-07-29 21:36 UTC, Gazizonoki commented on .github/workflows/examples.yaml
> -concurrency:
А зачем убрал concurrency? Ты так не сможешь отменить examples, если зависнет

2024-07-29 21:36 UTC, Gazizonoki commented on tests/integration/basic_example_it/basic_example.h
> +struct RunArgs {
По кодстайлу правильно:
```suggestion
struct TRunArgs {
```

2024-07-29 21:36 UTC, Gazizonoki commented on tests/integration/basic_example_it/basic_example.cpp
> +                return resultScanQuery;
Здесь надо возвращать статус последнего парта, а не самого ScanQuery, там то само собой success будет

2024-07-29 21:36 UTC, Gazizonoki commented on tests/integration/basic_example_it/basic_example.cpp
> +    return resultScanQuery;
Тут тоже

2024-07-30 08:53 UTC, stanislav-shchetinin commented on tests/integration/basic_example_it/basic_example.cpp
> +    return resultScanQuery;
У последнего куска результат - EOS, значит мне нужно возвращать результат предпоследнего кусочка - поддержание предпоследнего куска + обработка случаев, когда в первом же куске EOS раздует код. Если дошло до этой строчки, то результат SUCCESS в любом случае. Может я буду тогда возвращать что-то типа TStatus(EStatus::SUCCESS, NYql::TIssues())? Не знаю пустой ли TIssues у SUCCESS кусков, но даже если не пустой, то он потом все равно нигде не обрабатывается.

2024-07-30 15:16 UTC, Gazizonoki commented on .github/workflows/examples.yaml
> +    concurrency:
Не туда засунул, надо на уровень workflow положить

2024-07-30 15:16 UTC, Gazizonoki commented on tests/integration/basic_example_it/basic_example.h
> +#include <gtest/gtest.h>
А зачем здесь этот include?

2024-07-30 16:32 UTC, merged