Bulk upsert integration test
ydb-platform/ydb-cpp-sdk pull request #280
Opened 2024-07-31 14:44 UTC by stanislav-shchetinin

2024-07-31 16:04 UTC, Gazizonoki requested changes

2024-07-31 16:04 UTC, Gazizonoki commented on tests/integration/bulk_upsert_simple_it/bulk_upsert.cpp
> +        message.pk.App = "App_" + ToString(logOffset % 10);
Лучше используй std::to_string

2024-08-01 09:12 UTC, stanislav-shchetinin commented on tests/integration/bulk_upsert_simple_it/main.cpp
> +    std::set <TLogMessage> setMessage;
Согласен, лучше хранить TLogMessage::TPrimaryKeyLogMessage, "PK сделать уникальным" - не понял что ты имеешь ввиду

2024-08-01 10:29 UTC, stanislav-shchetinin commented on tests/integration/bulk_upsert_simple_it/main.cpp
> +        auto [batchSumApp, batchSumHost, batchRowCount] = GetLogBatch(offset, logBatch, setMessage);
Да, потому что размер set'а и будет суммой batchRowCount по всем батчам, еще одну структуру (без rowCount)  под этот случай я подумал, что создавать будет лишним, но чтобы не смущало, сделал еще переменную correctRowCount, которая будет суммой batchRowCount для всех батчей. В тесте теперь сравниваю с correctRowCoun, а не размером сета

2024-08-01 10:41 UTC, Gazizonoki commented on tests/integration/bulk_upsert_simple_it/main.cpp
> +    std::set <TLogMessage> setMessage;
Если сделать первичный ключ уникальным, то в сете вообще смысл отпадет. Даже сейчас, если посмотреть на ключ, шанс того, что он совпадет очень маленький. Можно вставить в него серийный счетчик какой-нибудь и все должно заработать

2024-08-01 17:46 UTC, Gazizonoki requested changes

2024-08-01 17:46 UTC, Gazizonoki commented on tests/integration/bulk_upsert_simple_it/bulk_upsert.cpp
> +    std::cerr << "Create table " << table << "\n";
А зачем тут этот cerr?

2024-08-01 17:46 UTC, Gazizonoki commented on tests/integration/bulk_upsert_simple_it/bulk_upsert.cpp
> +        message.pk = correctRowCount + lastNumber;
А вот так лучше не делать. Если вы грузим BulkUpsert'ом по возрастающему ключу, мы грузим всегда последнюю партицию, из-за этого мы будем тормозить, а еще хотелось бы, чтобы в тесте патриции все нагружались, мне кажется, так тесте больше кейсов покроет. Верни primary key старый, а эту колонку добавь в конец primary key. Так оно будет грузить таблицу равномерно

2024-08-01 17:46 UTC, Gazizonoki commented on tests/integration/bulk_upsert_simple_it/bulk_upsert.cpp
> +    TResultSetParser parser(*resultSet);
Провалидируй еще, что в result set'е ровно 1 строка и 3 колонки

2024-08-01 17:46 UTC, Gazizonoki commented on tests/integration/bulk_upsert_simple_it/bulk_upsert.h
> +    uint64_t pk;
Неправильный кодстайл
```suggestion
    uint64_t Pk;
```

2024-08-01 17:46 UTC, Gazizonoki commented on tests/integration/bulk_upsert_simple_it/bulk_upsert.h
> +    uint64_t sumApp;
Тут тоже все с большой буквы должно быть

2024-08-01 17:46 UTC, Gazizonoki commented on tests/integration/bulk_upsert_simple_it/bulk_upsert.h
> +    TDriver driver;
Тут тоже с большой

2024-08-01 20:46 UTC, stanislav-shchetinin commented on tests/integration/bulk_upsert_simple_it/bulk_upsert.cpp
> +        message.pk = correctRowCount + lastNumber;
Сделал, но я мало что понял из объяснения почему это плохо...

2024-08-02 07:20 UTC, stanislav-shchetinin commented on tests/integration/bulk_upsert_simple_it/bulk_upsert.cpp
> +    TResultSetParser parser(*resultSet);
Сделал, но не уверен, что правильно код ошибки выбрал

2024-08-02 19:21 UTC, Gazizonoki commented on tests/integration/bulk_upsert_simple_it/bulk_upsert.cpp
> +    TResultSetParser parser(*resultSet);
Тут любая пойдет

2024-08-02 19:23 UTC, Gazizonoki commented on tests/integration/bulk_upsert_simple_it/bulk_upsert.h
> +        bool operator<(const TPrimaryKeyLogMessage& o) const;
А зачем тебе оператор сравнения?

2024-08-02 19:43 UTC, merged