59 Replace THashSet to std::unordered_set
ydb-platform/ydb-cpp-sdk pull request #96
Opened 2024-03-14 09:57 UTC by SvRgK11010

2024-03-14 10:10 UTC, GitSparTV commented
PR для #59

2024-03-14 11:41 UTC, Gazizonoki requested changes
Ты не убрала сам файл с THashSet и его тестами в util. Их надо убрать

2024-03-14 16:30 UTC, SvRgK11010 commented on client/ydb_persqueue_core/ut/read_session_ut.cpp
> +        with_lock (Lock) {
в файле с  THashSet есть еще класс THashMultiset. Он нечасто встречается, могу его тогда в этой же задаче перенести? Если да, то по аналогии с другими задачами контейнер будет std::multiset?

2024-03-14 16:56 UTC, Gazizonoki commented on client/ydb_persqueue_core/ut/read_session_ut.cpp
> +        with_lock (Lock) {
Да, можешь поменять, только на [std::unordered_multiset](https://en.cppreference.com/w/cpp/container/unordered_multiset)

2024-04-07 09:48 UTC, SvRgK11010 commented
@GitSparTV исправила конфликты и ошибку сборки

2024-04-07 10:35 UTC, GitSparTV requested changes
Привет. Ура! Конфликты решены. Критичного ничего нет, но коммитик один понадобится

2024-04-07 10:35 UTC, GitSparTV commented on library/cpp/cache/cache.h
> +
строчка пришла лишняя

2024-04-07 10:35 UTC, GitSparTV commented on library/cpp/getopt/small/last_getopt_opt.h
> +//#include <util/generic/hash_set.h>
Остался комментарий

2024-04-07 12:40 UTC, SvRgK11010 commented on library/cpp/getopt/small/last_getopt_opt.h
> +//#include <util/generic/hash_set.h>
@GitSparTV готово.

2024-04-08 18:55 UTC, GitSparTV approved these changes
Отлично!

2024-04-09 13:11 UTC, Gazizonoki requested changes
В целом никаких проблем нет, замечания по мелочи. Поправь сегодня, пожалуйста

2024-04-09 19:42 UTC, Gazizonoki approved these changes

2024-04-09 19:42 UTC, merged